#DEV environment

app:
  message: This is the property file for the ${spring.application.name} - HEHE

spring:
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:me:db;DB_CLOSE_DELAY=-1
      username: as
      password: sa